server:
  port: 8090

spring:
  application:
     name: consumer-test

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://myusername:pass123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
# ribbon 客户端服务负载
provider-test:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# feign 请求压缩
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048