server:
  port: 8011
spring:
  application:
     name: provider-test

eureka:
  client:
    serviceUrl:
      defaultZone: http://myusername:pass123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true